/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_getstream_webrtc_SimulcastVideoEncoder */

#ifndef _Included_io_getstream_webrtc_SimulcastVideoEncoder
#define _Included_io_getstream_webrtc_SimulcastVideoEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_getstream_webrtc_SimulcastVideoEncoder
 * Method:    nativeCreateEncoder
 * Signature: (Lorg/webrtc/VideoEncoderFactory;Lorg/webrtc/VideoEncoderFactory;Lorg/webrtc/VideoCodecInfo;)J
 */

JNIEXPORT jlong JNICALL Java_io_getstream_webrtc_SimulcastVideoEncoder_nativeCreateEncoder
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
