/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io.getstream.webrtc_SimulcastVideoEncoderFactory */

#ifndef _Included_io.getstream.webrtc_SimulcastVideoEncoderFactory
#define _Included_io.getstream.webrtc_SimulcastVideoEncoderFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io.getstream.webrtc_SimulcastVideoEncoderFactory
 * Method:    nativeVP9Codecs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_io.getstream.webrtc_SimulcastVideoEncoderFactory_nativeVP9Codecs
  (JNIEnv *, jclass);

/*
 * Class:     io.getstream.webrtc_SimulcastVideoEncoderFactory
 * Method:    nativeAV1Codec
 * Signature: ()Lio.getstream.webrtc/VideoCodecInfo;
 */
JNIEXPORT jobject JNICALL Java_io.getstream.webrtc_SimulcastVideoEncoderFactory_nativeAV1Codec
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
