/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io.getstream.webrtc_SimulcastVideoEncoder */

#ifndef _Included_io.getstream.webrtc_SimulcastVideoEncoder
#define _Included_io.getstream.webrtc_SimulcastVideoEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io.getstream.webrtc_SimulcastVideoEncoder
 * Method:    nativeCreateEncoder
 * Signature: (Lio.getstream.webrtc/VideoEncoderFactory;Lio.getstream.webrtc/VideoEncoderFactory;Lio.getstream.webrtc/VideoCodecInfo;)J
 */

JNIEXPORT jlong JNICALL Java_io.getstream.webrtc_SimulcastVideoEncoder_nativeCreateEncoder
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
