# Copyright (c) 2019 The WebRTC project authors. All Rights Reserved.
#
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file in the root of the source
# tree. An additional intellectual property rights grant can be found
# in the file PATENTS.  All contributing project authors may
# be found in the AUTHORS file in the root of the source tree.

import("../../webrtc.gni")

group("crypto") {
  deps = [
    ":frame_decryptor_interface",
    ":frame_encryptor_interface",
    ":options",
  ]
}

# Header-only so Stream framing can include TrackType without depending on
# frame_crypto_transformer.cc (which constructs DefaultEncryptionManager).
rtc_source_set("frame_crypto_transformer_api") {
  visibility = [ "*" ]
  sources = [ "frame_crypto_transformer.h" ]
  deps = [
    "..:frame_transformer_interface",
    "..:make_ref_counted",
    "..:rtc_error",
    "../../rtc_base:buffer",
    "../../rtc_base:threading",
    "../../rtc_base/synchronization:mutex",
    "../../rtc_base/system:rtc_export",
    "../task_queue",
    "../task_queue:pending_task_safety_flag",
  ]
}

# STREAM-CUSTOM: JS-compatible framed AES-GCM. Isolated so m-branch syncs
# only touch frame_crypto_transformer sources, not this list.
# source_set (not rtc_library): DefaultEncryptionManager::CreateEncryptor
# constructs FrameCryptorTransformer, whose .cc constructs the manager.
rtc_source_set("frame_encryption") {
  visibility = [ "*" ]
  sources = [
    "default_encryption_manager.cc",
    "default_encryption_manager.h",
    "frame_crypto_codec.cc",
    "frame_crypto_codec.h",
    "frame_crypto_replay.cc",
    "frame_crypto_replay.h",
    "frame_crypto_replay_epoch.cc",
    "frame_crypto_replay_epoch.h",
    "frame_crypto_replay_window.cc",
    "frame_crypto_replay_window.h",
    "frame_crypto_trailer.cc",
    "frame_crypto_trailer.h",
    "frame_encryption_manager.h",
  ]

  public_deps = [ ":frame_crypto_transformer_api" ]

  deps = [
    "..:array_view",
    "..:ref_count",
    "..:scoped_refptr",
    "../../common_video",
    "../../rtc_base:buffer",
    "../../rtc_base:byte_buffer",
    "../../rtc_base:crypto_random",
    "../../rtc_base:logging",
    "../../rtc_base:platform_thread",
    "../../rtc_base:rtc_event",
    "../../rtc_base:threading",
    "../../rtc_base:timeutils",
    "../../rtc_base/synchronization:mutex",
    "../../rtc_base/system:rtc_export",
    "../task_queue",
    "../task_queue:pending_task_safety_flag",
    "../units:time_delta",
    "../video:video_frame",
  ]

  if (rtc_build_ssl) {
    deps += [ "//third_party/boringssl" ]
  } else {
    configs += [ ":external_ssl_library" ]
  }
}

rtc_library("frame_crypto_transformer") {
  visibility = [ "*" ]
  sources = [ "frame_crypto_transformer.cc" ]

  public_deps = [
    ":frame_crypto_transformer_api",
    ":frame_encryption",
  ]

  deps = [
    "..:array_view",
    "..:frame_transformer_interface",
    "..:make_ref_counted",
    "..:ref_count",
    "..:rtc_error",
    "..:scoped_refptr",
    "../../common_video",
    "../../modules/rtp_rtcp",
    "../../rtc_base:buffer",
    "../../rtc_base:byte_buffer",
    "../../rtc_base:crypto_random",
    "../../rtc_base:logging",
    "../../rtc_base:platform_thread",
    "../../rtc_base:rtc_event",
    "../../rtc_base:threading",
    "../../rtc_base:timeutils",
    "../../rtc_base/synchronization:mutex",
    "../../rtc_base/system:rtc_export",
    "../task_queue",
    "../task_queue:pending_task_safety_flag",
    "../units:timestamp",
    "../video:video_frame",
    "../video:video_frame_metadata",
    "//third_party/abseil-cpp/absl/container:inlined_vector",
    "//third_party/abseil-cpp/absl/functional:any_invocable",
    "//third_party/abseil-cpp/absl/types:variant",
  ]

  if (rtc_build_ssl) {
    deps += [ "//third_party/boringssl" ]
  } else {
    configs += [ ":external_ssl_library" ]
  }
}

rtc_library("options") {
  visibility = [ "*" ]
  sources = [
    "crypto_options.cc",
    "crypto_options.h",
  ]
  deps = [
    "..:field_trials_view",
    "../../rtc_base:checks",
    "../../rtc_base:ssl_adapter",
    "../../rtc_base/system:rtc_export",
    "//third_party/abseil-cpp/absl/algorithm:container",
  ]
}

rtc_source_set("frame_decryptor_interface") {
  visibility = [ "*" ]
  sources = [ "frame_decryptor_interface.h" ]
  deps = [
    "..:array_view",
    "..:ref_count",
    "..:rtp_parameters",
    "../../rtc_base:refcount",
  ]
}

rtc_source_set("frame_encryptor_interface") {
  visibility = [ "*" ]
  sources = [ "frame_encryptor_interface.h" ]
  deps = [
    "..:array_view",
    "..:ref_count",
    "..:rtp_parameters",
    "../../rtc_base:refcount",
  ]
}

if (rtc_include_tests) {
  rtc_library("crypto_options_unittest") {
    visibility = [ "*" ]
    testonly = true
    sources = [ "crypto_options_unittest.cc" ]
    deps = [
      ":options",
      "..:field_trials",
      "../../rtc_base:ssl_adapter",
      "../../test:create_test_field_trials",
      "../../test:test_support",
      "//testing/gtest",
    ]
    if (rtc_build_ssl) {
      deps += [ "//third_party/boringssl" ]
    }
  }

  rtc_library("frame_encryption_unittest") {
    visibility = [ "*" ]
    testonly = true
    sources = [
      "default_encryption_manager_unittest.cc",
      "frame_crypto_codec_unittest.cc",
      "frame_crypto_replay_epoch_unittest.cc",
      "frame_crypto_replay_unittest.cc",
      "frame_crypto_replay_window_unittest.cc",
      "frame_crypto_trailer_unittest.cc",
    ]
    deps = [
      ":frame_crypto_transformer",
      ":frame_encryption",
      "..:make_ref_counted",
      "../../rtc_base:logging",
      "../../rtc_base:threading",
      "../../test:test_support",
      "//testing/gtest",
    ]
    if (rtc_build_ssl) {
      deps += [ "//third_party/boringssl" ]
    }
  }

  rtc_library("frame_crypto_transformer_unittest") {
    visibility = [ "*" ]
    testonly = true
    sources = [ "frame_crypto_transformer_unittest.cc" ]
    deps = [
      ":frame_crypto_transformer",
      ":frame_encryption_unittest",
      "..:make_ref_counted",
      "..:mock_transformable_audio_frame",
      "..:mock_transformable_video_frame",
      "../../rtc_base:logging",
      "../../rtc_base:rtc_event",
      "../../rtc_base:threading",
      "../../test:test_support",
      "../video:video_frame",
      "../video:video_frame_metadata",
      "//testing/gtest",
    ]
    if (rtc_build_ssl) {
      deps += [ "//third_party/boringssl" ]
    }
  }

  # ponytail: standalone binary so we can land without ninja of full rtc_unittests.
  rtc_test("frame_crypto_transformer_unittests") {
    testonly = true
    deps = [ ":frame_crypto_transformer_unittest" ]
  }
}
