import("../../../webrtc.gni")
import("//build/config/android/config.gni")
import("//build/config/android/rules.gni")
import("//third_party/jni_zero/jni_zero.gni")

rtc_library("simulcast_jni") {
  visibility = [ "*" ]
  allow_poison = [ "software_video_codecs" ]
  sources = [
    "src/simulcast_video_encoder.cc",
    "src/simulcast_video_encoder.h",
    "src/simulcast_video_encoder_factory.cc",
    "src/simulcast_video_encoder_factory.h",
  ]
  deps = [
    "../../../sdk/android:base_jni",
    "../../../sdk/android:video_jni",
    "../../../sdk/android:native_api_codecs",
    "../../../media:rtc_simulcast_encoder_adapter",
    "../../../modules/video_coding/codecs/av1:av1_svc_config",
    "../../../modules/video_coding:webrtc_vp9",
    "../../../media:rtc_media_base",
    "../../../api/video_codecs:video_codecs_api",
    "../../../api:rtp_parameters",
    "../../../rtc_base:logging",
    "//third_party/abseil-cpp/absl/container:inlined_vector",
    "//third_party/jni_zero",
  ]
}

rtc_android_library("simulcast_java") {
  visibility = [ "*" ]
  sources = [
    "java/org/webrtc/SimulcastVideoEncoder.java",
    "java/org/webrtc/SimulcastVideoEncoderFactory.java",
    "java/org/webrtc/SimulcastAlignedVideoEncoderFactory.java",
    "java/org/webrtc/DefaultAlignedVideoEncoderFactory.java",
  ]
  deps = [
    "../../../extensions/android/utilities:utilities_java",
    "../../../sdk/android:hwcodecs_java",
    "../../../sdk/android:swcodecs_java",
    "../../../sdk/android:video_api_java",
    "../../../sdk/android:video_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
  ]
}
